Repository open-format/community-platform, pull requests merged in 2025-03, with the labels that each got.

#14 feat: Add API Key Generation to Community Platform
  .env.example
  messages/en.json
  src/app/(authenticated)/communities/layout.tsx
  src/components/community-profile.tsx
  src/components/profile-header.tsx
  src/hooks/useApikey.ts
  src/lib/openformat.ts
Labels: enhancement

#21 chore: Remove showWalletLoginFirst option from wallet configuration
  src/app/providers.tsx
Labels: enhancement

#25 Update README with Privy settings information
  README.md
Labels: documentation

#23 Added multicall support to Batch Rewards functionality
  @types/index.d.ts
  messages/en.json
  src/abis/ERC20Base.ts
  src/forms/batch-rewards-form.tsx
  src/forms/batch-rewards-settings-form.tsx
  src/lib/chain.ts
Labels: enhancement

#30 Changed actionType to more explicit values
  @types/index.d.ts
  messages/en.json
  src/components/batch-reward-list.tsx
  src/constants/examples.ts
  src/forms/batch-rewards-form.tsx
  src/lib/chain.ts
Labels: enhancement

#29 Fix: Solved small html error in Leaderboard
  src/components/leaderboard.tsx
Labels: bug

#27 Added username and token search
  @types/index.d.ts
  bun.lockb
  messages/en.json
  package.json
  src/components/batch-reward-list.tsx
  src/constants/examples.ts
  src/forms/batch-rewards-form.tsx
  src/lib/chain.ts
  src/lib/privy.ts
Labels: enhancement

#32 fix: token symbol in leaderboard header
  src/components/leaderboard.tsx
Labels: bug

#44 chore: Update package.json to include @types/react-datepicker
  bun.lockb
  package.json
Labels: bug

#45 Removing react-datepicker from dependencies
  bun.lockb
  package.json
  src/forms/activity-export-form.tsx
Labels: enhancement
